# example:
# database: -- database name 
#   tableName: -- tableName
#     hiveKey1:HbaseKey1
#     hiveKey2:HbaseKey2
#     hiveKey3:HbaseKey3
#     hiveKey4:HbaseKey4
#     hiveKey5:HbaseKey5
#     hiveKey6:HbaseKey6
#     hiveKey7:HbaseKey7
#     hiveKey8:HbaseKey8
#     hiveKey9:HbaseKey9
#     ……

